PREFIX : <http://www.semanticweb.org/banzo/ontologies/2022/5/dbara#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xml: <http://www.w3.org/XML/1998/namespace>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
BASE <http://www.semanticweb.org/banzo/ontologies/2022/5/dbara#>

SELECT  ?recipe_name ?subject
	WHERE { 
		?subject rdfs:subClassOf :Recipe .
		?recipe_name rdfs:subClassOf ?subject
	 }